-- ---------------------------------------------------------------------------
-- V001 — ops.etl_execution_logs
--
-- The pipeline's own flight recorder. One row per run, written whether the run
-- succeeds or fails. This table is the data source for every Grafana panel and
-- every Discord alert we build later, which makes it the most important table
-- in the project — more important than the prices themselves, because prices
-- can be re-fetched and a lost audit trail cannot be reconstructed.
--
-- Created before commodity_prices because that table references this one.
--
-- Migrations are idempotent (IF NOT EXISTS) so re-running them is harmless.
-- ---------------------------------------------------------------------------

CREATE TABLE IF NOT EXISTS ops.etl_execution_logs (

    -- A UUID generated by the PYTHON process at the start of a run, not by the
    -- database. This is deliberate: the pipeline needs the id in hand before it
    -- writes anything, so it can stamp the same id onto every price row it
    -- loads. A BIGSERIAL would only be known after the INSERT returned, and
    -- would collide if we ever run pipelines against more than one database.
    run_id              UUID PRIMARY KEY,

    -- Which pipeline. Today there is only one, but an audit table that assumes
    -- a single producer has to be rebuilt the moment a second one appears.
    pipeline_name       TEXT        NOT NULL,

    -- TIMESTAMPTZ, never TIMESTAMP. TIMESTAMPTZ stores an absolute moment;
    -- plain TIMESTAMP stores a wall-clock reading with no timezone, so a run at
    -- "09:00" is ambiguous and two runs either side of a DST change cannot be
    -- ordered. Postgres stores TIMESTAMPTZ in UTC and converts on display.
    -- Your original design had a single `execution_time`, but that conflates
    -- "when did this happen" with "how long did it take" — we need both, and
    -- two timestamps also let us detect a run that started and never finished.
    started_at          TIMESTAMPTZ NOT NULL DEFAULT now(),
    finished_at         TIMESTAMPTZ,

    -- RUNNING is added to your original three. It is what makes the row
    -- insertable at the START of a run: we write RUNNING, do the work, then
    -- UPDATE to a terminal status. A row stuck in RUNNING is itself a signal —
    -- it means the process died so hard it could not even log its own failure,
    -- which a "write the row at the end" design can never detect.
    --
    -- CHECK rather than a Postgres ENUM type: adding a value to an ENUM is a
    -- schema migration and they are awkward to reorder, while a CHECK is a
    -- one-line ALTER. Either is defensible; CHECK is the lower-friction choice.
    status              TEXT        NOT NULL,

    -- Duration in milliseconds. Redundant with finished_at - started_at, and
    -- storing it anyway is a conscious trade: Grafana can plot latency without
    -- computing an interval on every query, and the value stays correct even
    -- if a clock adjustment makes the subtraction lie.
    latency_ms          INTEGER,

    records_processed   INTEGER,

    error_message       TEXT,

    -- ── The chaos switch's audit trail (used from Sprint 4) ────────────────
    -- Without these two columns, a simulated failure is indistinguishable from
    -- a real one after the fact, and every demo run would poison the real
    -- reliability numbers. Any Grafana panel measuring true success rate will
    -- filter on simulated_failure = FALSE.
    simulated_failure   BOOLEAN     NOT NULL DEFAULT FALSE,

    -- Which fault was injected: SCHEMA_MISMATCH, NULL_VALUES, NETWORK_TIMEOUT.
    -- NULL when nothing was injected.
    injected_fault      TEXT,

    CONSTRAINT ck_eel_status
        CHECK (status IN ('RUNNING', 'SUCCESS', 'FAILED', 'STALE_DATA')),

    -- A finished run must have a finish time, and a running one must not.
    -- Constraints like this stop impossible rows from ever existing, which is
    -- worth far more than validating in Python: the database is the last line
    -- of defence and it applies to every writer, including a careless manual
    -- UPDATE typed at 2am during an incident.
    CONSTRAINT ck_eel_finished_at_matches_status
        CHECK (
            (status = 'RUNNING' AND finished_at IS NULL)
            OR
            (status <> 'RUNNING' AND finished_at IS NOT NULL)
        ),

    -- A failure with no explanation is a useless alert. This forces whoever
    -- writes the FAILED row to say why.
    CONSTRAINT ck_eel_failure_has_message
        CHECK (status <> 'FAILED' OR error_message IS NOT NULL),

    -- An injected fault only makes sense on a simulated run.
    CONSTRAINT ck_eel_injected_fault_requires_simulation
        CHECK (injected_fault IS NULL OR simulated_failure = TRUE),

    CONSTRAINT ck_eel_latency_non_negative
        CHECK (latency_ms IS NULL OR latency_ms >= 0),

    CONSTRAINT ck_eel_records_non_negative
        CHECK (records_processed IS NULL OR records_processed >= 0)
);

-- Grafana's dashboards will overwhelmingly ask "what happened recently?",
-- which is an ORDER BY started_at DESC with a time filter. DESC in the index
-- matches that scan direction.
CREATE INDEX IF NOT EXISTS ix_eel_started_at
    ON ops.etl_execution_logs (started_at DESC);

-- A PARTIAL index: it only contains rows that are not successful. Since most
-- runs should succeed, this index stays tiny while making "show me the
-- failures" — the alerting query — very fast. Indexing the whole status column
-- would be far larger and much less useful, because an index is nearly
-- pointless on a column where one value dominates.
CREATE INDEX IF NOT EXISTS ix_eel_failures
    ON ops.etl_execution_logs (started_at DESC)
    WHERE status <> 'SUCCESS';

COMMENT ON TABLE ops.etl_execution_logs IS
    'One row per pipeline run. Feeds the Grafana dashboards and Discord alerts.';
COMMENT ON COLUMN ops.etl_execution_logs.simulated_failure IS
    'TRUE when the chaos switch caused this outcome. Exclude these rows when measuring real reliability.';
